name = "server-SG" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg1.apaantuh.my.id"
custom_domain = true
[[routes]]
pattern = "jjndi0k9m2.int.vidio.com.sg1.apaantuh.my.id"
custom_domain = true
[[routes]]
pattern = "app.vidio.com.sg1.apaantuh.my.id"
custom_domain = true


[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "dc9dd73c-1c54-4dfe-82d7-de243d1b41f0"
